name: 'Runtime Iac Action'

description: 'Runtime Iac Action'

inputs:
  FEATURES_LEVEL_LOG:
    description: Level log
    required: true
    default: "debug"
  FILE_PATH:
    description: File path
    required: true
    default: "iac.yaml"

runs:
  using: 'docker'
  steps:
  - name: 'Runtime Iac Action'
    image: docker://stackspot/runtime-iac:latest
    env:
      FEATURES_LEVEL_LOG: ${{ inputs.FEATURES_LEVEL_LOG }}
      FILE_PATH: ${{ inputs.FILE_PATH }}
    entrypoint: '/app/stackspot-runtime-job-iac start --input-path=/app/$FILE_PATH'
    volumes:
      - ${{ github.workspace }}:/app

branding:
    icon: 'terminal'
    color: 'gray-dark'
