name: 'Runtime Iac Action'

description: 'Runtime Iac Action'

inputs:
  LEVEL_LOG:
    description: Level log
    required: true
    default: "debug"
  FILE_PATH:
    description: File path
    required: true
    default: "iac.yaml"
runs:
  using: 'docker'
  image: 'stackspot/runtime-iac:latest'
  env:
    FEATURES_LEVEL_LOG: ${{ inputs.LEVEL_LOG }}
  entrypoint: '/app/stackspot-runtime-job-iac start --input-path=${{ inputs.FILE_PATH }}'

branding:
    icon: 'terminal'
    color: 'gray-dark'
