name: 'Runtime Iac Action'

description: 'Runtime Iac Action'

inputs:
  FEATURES_LEVEL_LOG:
    description: Level log
    required: true
    default: "debug"
  FILE_PATH:
    description: File path
    required: true
    default: "iac.yaml"

runs:
  using: 'docker'
  image: docker://stackspot/runtime-iac:latest
  env:
    FEATURES_LEVEL_LOG: ${{ inputs.FEATURES_LEVEL_LOG }}
    FILE_PATH: ${{ inputs.FILE_PATH }}
  args:
    - 'cp $FILE_PATH /app/iac.yaml'
    - 'ls -la /app'
  entrypoint: '/app/stackspot-runtime-job-iac start --input-path=iac.yaml'

branding:
    icon: 'terminal'
    color: 'gray-dark'
