name: "Run Docker Container"
description: "Executa um container Docker com parâmetros personalizados"
inputs:
  FEATURES_LEVEL_LOG:
    description: "Nível de log"
    required: true
  input_path:
    description: "Nome do arquivo para input-path"
    required: true

runs:
  using: "composite"
  steps:
    - name: Executar o Docker Container
      run: |
        docker run --rm \
        -e FEATURES_LEVEL_LOG=${{ inputs.FEATURES_LEVEL_LOG }} \
        --entrypoint=/app/stackspot-runtime-job-iac \
        stackspot/runtime-iac start --input-path=${{ inputs.input_path }}
      shell: bash
