name: Meu Workflow de Teste

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Executar minha action
      uses: ./.github/actions/run-docker-container
      with:
        FEATURES_LEVEL_LOG: debug
        input_path: iac.yaml
