name: Action Test Ubuntu

on:
  push:
    paths:
      - '.github/workflows/action-test-linux.yaml'
      - 'action.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check things
      run: tree

    - name: Check things 2
      run: ls -la

    - name: Prepare files
      run: echo  ${FILE_PATH} && cp ${FILE_PATH} /app/

    - name: Runtime Iac Action
      uses: rmnobarra/runtime-github-action-iac@main
      with:
        FEATURES_LEVEL_LOG: debug
        FILE_PATH: iac.yaml
  
