name: Meu Workflow de Teste

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Executar minha action
      uses: rmnobarra/runtime-github-action-iac@main
      with:
        FEATURES_LEVEL_LOG: debug
        input_path: iac.yaml
