name: Container Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://guillaumefalourd/ritchiecli:go-1.15.8

    steps:
      - name: Run Commands
        run: |
              sudo rit -v
              sudo go version